name: application

description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # share: any

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5

  mvc_pattern: ^8.12.0

  flutter_libphonenumber:
  # libphonenumber: ^2.0.2
  flutter_rounded_date_picker: ^3.0.4
  image_picker: ^1.0.0
  # file_picker: ^2.0.0
  cached_network_image: ^3.2.0
  mime_type: ^1.0.0
  flutter_phoenix: ^1.1.1
  simple_animations: ^5.0.2

  # location: ^3.0.0
  # geolocator: '6.2.1'
  # map_launcher: ^0.4.4

  flutter_html: any

  firebase_messaging: ^15.2.4

  firebase_core: ^3.13.0


  # google_sign_in: 4.0.6 #current version 4.4.4, reason unable to build
  firebase_auth: 5.5.2
  # flutter_facebook_login: ^3.0.0 <- incompatible with Dart 3, can replaced to flutter_login_facebook or flutter_facebook_auth (preferred)

  local_auth: ^2.1.6
  # kakao_flutter_sdk: ^1.7.0
  # kakao_flutter_sdk: ^1.2.2 #Kakao login (Android)
  sign_in_with_apple: ^6.1.4
  # flutter_naver_login: ^2.0.0 check later
  # fluwx_no_pay_ww: ^1.0.4

  dio: ^5.8.0+1

  shared_preferences: ^2.0.13

  get_it: ^8.0.3

  json_serializable: any
  json_annotation: ^4.6.0

  provider: ^6.0.5

  # barcode_scan: ^3.0.1 (could switch to barcode_scan2: 4.5.0)
  qr_code_scanner_plus: ^2.0.10+1
  # qr_code_scanner: ^1.0.1 (switch to qr_code_scanner_plus)
  # qr_code_tools: ^0.0.7 (no longer maintained)
  qr_flutter: ^4.0.0
  # barcode_flutter: ^1.1.2 (no longer maintained)
  selectable_autolink_text: ^2.3.0

  enum_to_string: ^2.0.1
  random_string: ^2.3.1
  device_info_plus: ^11.0.0
  firebase_analytics: ^11.4.4

  webview_flutter: 4.10.0
  advance_pdf_viewer2: ^2.0.5+1

  webview_flutter_wkwebview: ^3.18.2

  fl_chart: 0.70.2
  equatable: 2.0.7
  path_drawing: 1.0.1

  # panorama: 0.4.1 (could switch to panorama_viewer)
  panorama_viewer: 2.0.4
  flutter_downloader: 1.12.0
  flutter_bloc: 9.1.0
  # camera: 0.11.1
  # tflite: 1.1.1 (could switch to tflite_flutter)
  url_launcher: ^6.1.6
  # fluttertoast: 8.2.12 (cannot fixed due to Error 2)
  
  flutter_app_badger: ^1.5.0
  # flutter_windowmanager: 0.2.0 (could switch to flutter_windowmanager_plus)
  grouped_list:
  carousel_slider: 5.0.0
  barcode_widget: ^2.0.4
  devicelocale: ^0.8.1
  barcode_scan2: ^4.5.0
  qr_code_utils: ^0.0.3
  # scan: ^1.6.0 (this needed)
  
dependency_overrides:
  analyzer: ^4.1.0

dev_dependencies:
  flutter_test: 
    sdk: flutter
  
  # build_runner: ^2.1.2

  # flutter_launcher_icons: ^0.14.3
  # flutter_launcher_name: "^0.0.1"
  # package_info_plus: ^8.3.0

flutter:
  uses-material-design: true